import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1752434225632 implements MigrationInterface {
    name = 'Migration1752434225632'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user_settings" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "uuid" text NOT NULL, "username" text NOT NULL, "email" text, "isAdmin" boolean NOT NULL DEFAULT (0), "passwordHash" text NOT NULL, "settingsId" integer NOT NULL, CONSTRAINT "REL_390395c3d8592e3e8d8422ce85" UNIQUE ("settingsId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a95e949168be7b7ece1a2382fe" ON "user" ("uuid") `);
        await queryRunner.query(`CREATE TABLE "currency" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "code" varchar(3) NOT NULL, "visible" boolean NOT NULL DEFAULT (1), CONSTRAINT "UQ_723472e41cae44beb0763f4039c" UNIQUE ("code"))`);
        await queryRunner.query(`CREATE TABLE "account" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "balance" decimal(10,2) NOT NULL, "userId" integer NOT NULL, "currencyId" integer)`);
        await queryRunner.query(`CREATE TABLE "recurring_income" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "description" text NOT NULL, "amount" decimal(10,2) NOT NULL, "startDate" date NOT NULL, "frequency" text NOT NULL, "skipAmount" integer NOT NULL DEFAULT (0), "status" boolean NOT NULL DEFAULT (1), "userId" integer NOT NULL, "currencyId" integer, "accountId" integer)`);
        await queryRunner.query(`CREATE TABLE "tax" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "rate" decimal(5,2) NOT NULL, "userId" integer NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "payment_method" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "credit" boolean NOT NULL DEFAULT (0), "creditLimit" decimal(10,2), "status" boolean NOT NULL DEFAULT (1), "userId" integer NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "recurring_expense" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "description" text NOT NULL, "amount" decimal(10,2) NOT NULL, "startDate" date NOT NULL, "frequency" text NOT NULL, "skipAmount" integer NOT NULL DEFAULT (0), "status" boolean NOT NULL DEFAULT (1), "userId" integer NOT NULL, "currencyId" integer, "paymentMethodId" integer)`);
        await queryRunner.query(`CREATE TABLE "income" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "description" text NOT NULL, "amount" decimal(10,2) NOT NULL, "date" date NOT NULL, "userId" integer NOT NULL, "currencyId" integer NOT NULL, "accountId" integer NOT NULL, "recurringIncomeId" integer)`);
        await queryRunner.query(`CREATE TABLE "expense" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "description" text NOT NULL, "amount" decimal(10,2) NOT NULL, "date" date NOT NULL, "userId" integer NOT NULL, "currencyId" integer NOT NULL, "paymentMethodId" integer NOT NULL, "recurringExpenseId" integer)`);
        await queryRunner.query(`CREATE TABLE "exchange_rate" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rate" decimal(10,4) NOT NULL DEFAULT (1), "sourceApiUrl" text NOT NULL, "lastUpdated" date NOT NULL, "fromCurrencyId" integer NOT NULL, "toCurrencyId" integer NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "api_key" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "key" text NOT NULL, "userId" integer NOT NULL, CONSTRAINT "UQ_fb080786c16de6ace7ed0b69f7d" UNIQUE ("key"))`);
        await queryRunner.query(`CREATE TABLE "recurring_expense_taxes_tax" ("recurringExpenseId" integer NOT NULL, "taxId" integer NOT NULL, PRIMARY KEY ("recurringExpenseId", "taxId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ae12db69fd3a32f20aa527ff67" ON "recurring_expense_taxes_tax" ("recurringExpenseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b8337a489f9c302f23e1f5efd" ON "recurring_expense_taxes_tax" ("taxId") `);
        await queryRunner.query(`CREATE TABLE "expense_taxes_tax" ("expenseId" integer NOT NULL, "taxId" integer NOT NULL, PRIMARY KEY ("expenseId", "taxId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ae2ca2a322385d5d0461bcb908" ON "expense_taxes_tax" ("expenseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_302808fcd211d51ffaff57edf8" ON "expense_taxes_tax" ("taxId") `);
        await queryRunner.query(`DROP INDEX "IDX_a95e949168be7b7ece1a2382fe"`);
        await queryRunner.query(`CREATE TABLE "temporary_user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "uuid" text NOT NULL, "username" text NOT NULL, "email" text, "isAdmin" boolean NOT NULL DEFAULT (0), "passwordHash" text NOT NULL, "settingsId" integer NOT NULL, CONSTRAINT "REL_390395c3d8592e3e8d8422ce85" UNIQUE ("settingsId"), CONSTRAINT "FK_390395c3d8592e3e8d8422ce853" FOREIGN KEY ("settingsId") REFERENCES "user_settings" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_user"("id", "uuid", "username", "email", "isAdmin", "passwordHash", "settingsId") SELECT "id", "uuid", "username", "email", "isAdmin", "passwordHash", "settingsId" FROM "user"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`ALTER TABLE "temporary_user" RENAME TO "user"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a95e949168be7b7ece1a2382fe" ON "user" ("uuid") `);
        await queryRunner.query(`CREATE TABLE "temporary_account" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "balance" decimal(10,2) NOT NULL, "userId" integer NOT NULL, "currencyId" integer, CONSTRAINT "FK_60328bf27019ff5498c4b977421" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_f6cf13404290564d6992f5e4158" FOREIGN KEY ("currencyId") REFERENCES "currency" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_account"("id", "name", "balance", "userId", "currencyId") SELECT "id", "name", "balance", "userId", "currencyId" FROM "account"`);
        await queryRunner.query(`DROP TABLE "account"`);
        await queryRunner.query(`ALTER TABLE "temporary_account" RENAME TO "account"`);
        await queryRunner.query(`CREATE TABLE "temporary_recurring_income" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "description" text NOT NULL, "amount" decimal(10,2) NOT NULL, "startDate" date NOT NULL, "frequency" text NOT NULL, "skipAmount" integer NOT NULL DEFAULT (0), "status" boolean NOT NULL DEFAULT (1), "userId" integer NOT NULL, "currencyId" integer, "accountId" integer, CONSTRAINT "FK_c3984895184efaed4aa1a15833d" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_ecd01cf575b87648fe01b7f58f1" FOREIGN KEY ("currencyId") REFERENCES "currency" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_4cdeead1dd7ea9e917924fa4b6f" FOREIGN KEY ("accountId") REFERENCES "account" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_recurring_income"("id", "description", "amount", "startDate", "frequency", "skipAmount", "status", "userId", "currencyId", "accountId") SELECT "id", "description", "amount", "startDate", "frequency", "skipAmount", "status", "userId", "currencyId", "accountId" FROM "recurring_income"`);
        await queryRunner.query(`DROP TABLE "recurring_income"`);
        await queryRunner.query(`ALTER TABLE "temporary_recurring_income" RENAME TO "recurring_income"`);
        await queryRunner.query(`CREATE TABLE "temporary_tax" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "rate" decimal(5,2) NOT NULL, "userId" integer NOT NULL, CONSTRAINT "FK_207b215193adf5dbe49a7b2a659" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_tax"("id", "name", "rate", "userId") SELECT "id", "name", "rate", "userId" FROM "tax"`);
        await queryRunner.query(`DROP TABLE "tax"`);
        await queryRunner.query(`ALTER TABLE "temporary_tax" RENAME TO "tax"`);
        await queryRunner.query(`CREATE TABLE "temporary_payment_method" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "credit" boolean NOT NULL DEFAULT (0), "creditLimit" decimal(10,2), "status" boolean NOT NULL DEFAULT (1), "userId" integer NOT NULL, CONSTRAINT "FK_34a4419ef2010224d7ff600659d" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_payment_method"("id", "name", "credit", "creditLimit", "status", "userId") SELECT "id", "name", "credit", "creditLimit", "status", "userId" FROM "payment_method"`);
        await queryRunner.query(`DROP TABLE "payment_method"`);
        await queryRunner.query(`ALTER TABLE "temporary_payment_method" RENAME TO "payment_method"`);
        await queryRunner.query(`CREATE TABLE "temporary_recurring_expense" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "description" text NOT NULL, "amount" decimal(10,2) NOT NULL, "startDate" date NOT NULL, "frequency" text NOT NULL, "skipAmount" integer NOT NULL DEFAULT (0), "status" boolean NOT NULL DEFAULT (1), "userId" integer NOT NULL, "currencyId" integer, "paymentMethodId" integer, CONSTRAINT "FK_90f9f55ed1e7c51f8b6ae9220b7" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_3bb15ca76e04029081c3f30e28e" FOREIGN KEY ("currencyId") REFERENCES "currency" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5ee0c24d076e95895d46aae8479" FOREIGN KEY ("paymentMethodId") REFERENCES "payment_method" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_recurring_expense"("id", "description", "amount", "startDate", "frequency", "skipAmount", "status", "userId", "currencyId", "paymentMethodId") SELECT "id", "description", "amount", "startDate", "frequency", "skipAmount", "status", "userId", "currencyId", "paymentMethodId" FROM "recurring_expense"`);
        await queryRunner.query(`DROP TABLE "recurring_expense"`);
        await queryRunner.query(`ALTER TABLE "temporary_recurring_expense" RENAME TO "recurring_expense"`);
        await queryRunner.query(`CREATE TABLE "temporary_income" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "description" text NOT NULL, "amount" decimal(10,2) NOT NULL, "date" date NOT NULL, "userId" integer NOT NULL, "currencyId" integer NOT NULL, "accountId" integer NOT NULL, "recurringIncomeId" integer, CONSTRAINT "FK_0965fe0d5faa3b2e7518d7bb244" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_e63893cc5604abe13010c355be7" FOREIGN KEY ("currencyId") REFERENCES "currency" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_278726c015edbc72a6c1b3196ea" FOREIGN KEY ("accountId") REFERENCES "account" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_98abda23d393a101589bcf07ae2" FOREIGN KEY ("recurringIncomeId") REFERENCES "recurring_income" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_income"("id", "description", "amount", "date", "userId", "currencyId", "accountId", "recurringIncomeId") SELECT "id", "description", "amount", "date", "userId", "currencyId", "accountId", "recurringIncomeId" FROM "income"`);
        await queryRunner.query(`DROP TABLE "income"`);
        await queryRunner.query(`ALTER TABLE "temporary_income" RENAME TO "income"`);
        await queryRunner.query(`CREATE TABLE "temporary_expense" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "description" text NOT NULL, "amount" decimal(10,2) NOT NULL, "date" date NOT NULL, "userId" integer NOT NULL, "currencyId" integer NOT NULL, "paymentMethodId" integer NOT NULL, "recurringExpenseId" integer, CONSTRAINT "FK_06e076479515578ab1933ab4375" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_cf05486337b769f6c0e0cd1fac0" FOREIGN KEY ("currencyId") REFERENCES "currency" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_e513c04b25aa5b3d760b7b78fbd" FOREIGN KEY ("paymentMethodId") REFERENCES "payment_method" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_922a70347145932afd138b19578" FOREIGN KEY ("recurringExpenseId") REFERENCES "recurring_expense" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_expense"("id", "description", "amount", "date", "userId", "currencyId", "paymentMethodId", "recurringExpenseId") SELECT "id", "description", "amount", "date", "userId", "currencyId", "paymentMethodId", "recurringExpenseId" FROM "expense"`);
        await queryRunner.query(`DROP TABLE "expense"`);
        await queryRunner.query(`ALTER TABLE "temporary_expense" RENAME TO "expense"`);
        await queryRunner.query(`CREATE TABLE "temporary_exchange_rate" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rate" decimal(10,4) NOT NULL DEFAULT (1), "sourceApiUrl" text NOT NULL, "lastUpdated" date NOT NULL, "fromCurrencyId" integer NOT NULL, "toCurrencyId" integer NOT NULL, CONSTRAINT "FK_04df2528e89d929794b1171e5e4" FOREIGN KEY ("fromCurrencyId") REFERENCES "currency" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_4896136338c8f2110ac489d91b2" FOREIGN KEY ("toCurrencyId") REFERENCES "currency" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_exchange_rate"("id", "rate", "sourceApiUrl", "lastUpdated", "fromCurrencyId", "toCurrencyId") SELECT "id", "rate", "sourceApiUrl", "lastUpdated", "fromCurrencyId", "toCurrencyId" FROM "exchange_rate"`);
        await queryRunner.query(`DROP TABLE "exchange_rate"`);
        await queryRunner.query(`ALTER TABLE "temporary_exchange_rate" RENAME TO "exchange_rate"`);
        await queryRunner.query(`CREATE TABLE "temporary_api_key" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "key" text NOT NULL, "userId" integer NOT NULL, CONSTRAINT "UQ_fb080786c16de6ace7ed0b69f7d" UNIQUE ("key"), CONSTRAINT "FK_277972f4944205eb29127f9bb6c" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_api_key"("id", "key", "userId") SELECT "id", "key", "userId" FROM "api_key"`);
        await queryRunner.query(`DROP TABLE "api_key"`);
        await queryRunner.query(`ALTER TABLE "temporary_api_key" RENAME TO "api_key"`);
        await queryRunner.query(`DROP INDEX "IDX_ae12db69fd3a32f20aa527ff67"`);
        await queryRunner.query(`DROP INDEX "IDX_6b8337a489f9c302f23e1f5efd"`);
        await queryRunner.query(`CREATE TABLE "temporary_recurring_expense_taxes_tax" ("recurringExpenseId" integer NOT NULL, "taxId" integer NOT NULL, CONSTRAINT "FK_ae12db69fd3a32f20aa527ff671" FOREIGN KEY ("recurringExpenseId") REFERENCES "recurring_expense" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_6b8337a489f9c302f23e1f5efd6" FOREIGN KEY ("taxId") REFERENCES "tax" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("recurringExpenseId", "taxId"))`);
        await queryRunner.query(`INSERT INTO "temporary_recurring_expense_taxes_tax"("recurringExpenseId", "taxId") SELECT "recurringExpenseId", "taxId" FROM "recurring_expense_taxes_tax"`);
        await queryRunner.query(`DROP TABLE "recurring_expense_taxes_tax"`);
        await queryRunner.query(`ALTER TABLE "temporary_recurring_expense_taxes_tax" RENAME TO "recurring_expense_taxes_tax"`);
        await queryRunner.query(`CREATE INDEX "IDX_ae12db69fd3a32f20aa527ff67" ON "recurring_expense_taxes_tax" ("recurringExpenseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b8337a489f9c302f23e1f5efd" ON "recurring_expense_taxes_tax" ("taxId") `);
        await queryRunner.query(`DROP INDEX "IDX_ae2ca2a322385d5d0461bcb908"`);
        await queryRunner.query(`DROP INDEX "IDX_302808fcd211d51ffaff57edf8"`);
        await queryRunner.query(`CREATE TABLE "temporary_expense_taxes_tax" ("expenseId" integer NOT NULL, "taxId" integer NOT NULL, CONSTRAINT "FK_ae2ca2a322385d5d0461bcb9084" FOREIGN KEY ("expenseId") REFERENCES "expense" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_302808fcd211d51ffaff57edf8f" FOREIGN KEY ("taxId") REFERENCES "tax" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("expenseId", "taxId"))`);
        await queryRunner.query(`INSERT INTO "temporary_expense_taxes_tax"("expenseId", "taxId") SELECT "expenseId", "taxId" FROM "expense_taxes_tax"`);
        await queryRunner.query(`DROP TABLE "expense_taxes_tax"`);
        await queryRunner.query(`ALTER TABLE "temporary_expense_taxes_tax" RENAME TO "expense_taxes_tax"`);
        await queryRunner.query(`CREATE INDEX "IDX_ae2ca2a322385d5d0461bcb908" ON "expense_taxes_tax" ("expenseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_302808fcd211d51ffaff57edf8" ON "expense_taxes_tax" ("taxId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_302808fcd211d51ffaff57edf8"`);
        await queryRunner.query(`DROP INDEX "IDX_ae2ca2a322385d5d0461bcb908"`);
        await queryRunner.query(`ALTER TABLE "expense_taxes_tax" RENAME TO "temporary_expense_taxes_tax"`);
        await queryRunner.query(`CREATE TABLE "expense_taxes_tax" ("expenseId" integer NOT NULL, "taxId" integer NOT NULL, PRIMARY KEY ("expenseId", "taxId"))`);
        await queryRunner.query(`INSERT INTO "expense_taxes_tax"("expenseId", "taxId") SELECT "expenseId", "taxId" FROM "temporary_expense_taxes_tax"`);
        await queryRunner.query(`DROP TABLE "temporary_expense_taxes_tax"`);
        await queryRunner.query(`CREATE INDEX "IDX_302808fcd211d51ffaff57edf8" ON "expense_taxes_tax" ("taxId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae2ca2a322385d5d0461bcb908" ON "expense_taxes_tax" ("expenseId") `);
        await queryRunner.query(`DROP INDEX "IDX_6b8337a489f9c302f23e1f5efd"`);
        await queryRunner.query(`DROP INDEX "IDX_ae12db69fd3a32f20aa527ff67"`);
        await queryRunner.query(`ALTER TABLE "recurring_expense_taxes_tax" RENAME TO "temporary_recurring_expense_taxes_tax"`);
        await queryRunner.query(`CREATE TABLE "recurring_expense_taxes_tax" ("recurringExpenseId" integer NOT NULL, "taxId" integer NOT NULL, PRIMARY KEY ("recurringExpenseId", "taxId"))`);
        await queryRunner.query(`INSERT INTO "recurring_expense_taxes_tax"("recurringExpenseId", "taxId") SELECT "recurringExpenseId", "taxId" FROM "temporary_recurring_expense_taxes_tax"`);
        await queryRunner.query(`DROP TABLE "temporary_recurring_expense_taxes_tax"`);
        await queryRunner.query(`CREATE INDEX "IDX_6b8337a489f9c302f23e1f5efd" ON "recurring_expense_taxes_tax" ("taxId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae12db69fd3a32f20aa527ff67" ON "recurring_expense_taxes_tax" ("recurringExpenseId") `);
        await queryRunner.query(`ALTER TABLE "api_key" RENAME TO "temporary_api_key"`);
        await queryRunner.query(`CREATE TABLE "api_key" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "key" text NOT NULL, "userId" integer NOT NULL, CONSTRAINT "UQ_fb080786c16de6ace7ed0b69f7d" UNIQUE ("key"))`);
        await queryRunner.query(`INSERT INTO "api_key"("id", "key", "userId") SELECT "id", "key", "userId" FROM "temporary_api_key"`);
        await queryRunner.query(`DROP TABLE "temporary_api_key"`);
        await queryRunner.query(`ALTER TABLE "exchange_rate" RENAME TO "temporary_exchange_rate"`);
        await queryRunner.query(`CREATE TABLE "exchange_rate" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rate" decimal(10,4) NOT NULL DEFAULT (1), "sourceApiUrl" text NOT NULL, "lastUpdated" date NOT NULL, "fromCurrencyId" integer NOT NULL, "toCurrencyId" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "exchange_rate"("id", "rate", "sourceApiUrl", "lastUpdated", "fromCurrencyId", "toCurrencyId") SELECT "id", "rate", "sourceApiUrl", "lastUpdated", "fromCurrencyId", "toCurrencyId" FROM "temporary_exchange_rate"`);
        await queryRunner.query(`DROP TABLE "temporary_exchange_rate"`);
        await queryRunner.query(`ALTER TABLE "expense" RENAME TO "temporary_expense"`);
        await queryRunner.query(`CREATE TABLE "expense" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "description" text NOT NULL, "amount" decimal(10,2) NOT NULL, "date" date NOT NULL, "userId" integer NOT NULL, "currencyId" integer NOT NULL, "paymentMethodId" integer NOT NULL, "recurringExpenseId" integer)`);
        await queryRunner.query(`INSERT INTO "expense"("id", "description", "amount", "date", "userId", "currencyId", "paymentMethodId", "recurringExpenseId") SELECT "id", "description", "amount", "date", "userId", "currencyId", "paymentMethodId", "recurringExpenseId" FROM "temporary_expense"`);
        await queryRunner.query(`DROP TABLE "temporary_expense"`);
        await queryRunner.query(`ALTER TABLE "income" RENAME TO "temporary_income"`);
        await queryRunner.query(`CREATE TABLE "income" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "description" text NOT NULL, "amount" decimal(10,2) NOT NULL, "date" date NOT NULL, "userId" integer NOT NULL, "currencyId" integer NOT NULL, "accountId" integer NOT NULL, "recurringIncomeId" integer)`);
        await queryRunner.query(`INSERT INTO "income"("id", "description", "amount", "date", "userId", "currencyId", "accountId", "recurringIncomeId") SELECT "id", "description", "amount", "date", "userId", "currencyId", "accountId", "recurringIncomeId" FROM "temporary_income"`);
        await queryRunner.query(`DROP TABLE "temporary_income"`);
        await queryRunner.query(`ALTER TABLE "recurring_expense" RENAME TO "temporary_recurring_expense"`);
        await queryRunner.query(`CREATE TABLE "recurring_expense" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "description" text NOT NULL, "amount" decimal(10,2) NOT NULL, "startDate" date NOT NULL, "frequency" text NOT NULL, "skipAmount" integer NOT NULL DEFAULT (0), "status" boolean NOT NULL DEFAULT (1), "userId" integer NOT NULL, "currencyId" integer, "paymentMethodId" integer)`);
        await queryRunner.query(`INSERT INTO "recurring_expense"("id", "description", "amount", "startDate", "frequency", "skipAmount", "status", "userId", "currencyId", "paymentMethodId") SELECT "id", "description", "amount", "startDate", "frequency", "skipAmount", "status", "userId", "currencyId", "paymentMethodId" FROM "temporary_recurring_expense"`);
        await queryRunner.query(`DROP TABLE "temporary_recurring_expense"`);
        await queryRunner.query(`ALTER TABLE "payment_method" RENAME TO "temporary_payment_method"`);
        await queryRunner.query(`CREATE TABLE "payment_method" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "credit" boolean NOT NULL DEFAULT (0), "creditLimit" decimal(10,2), "status" boolean NOT NULL DEFAULT (1), "userId" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "payment_method"("id", "name", "credit", "creditLimit", "status", "userId") SELECT "id", "name", "credit", "creditLimit", "status", "userId" FROM "temporary_payment_method"`);
        await queryRunner.query(`DROP TABLE "temporary_payment_method"`);
        await queryRunner.query(`ALTER TABLE "tax" RENAME TO "temporary_tax"`);
        await queryRunner.query(`CREATE TABLE "tax" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "rate" decimal(5,2) NOT NULL, "userId" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "tax"("id", "name", "rate", "userId") SELECT "id", "name", "rate", "userId" FROM "temporary_tax"`);
        await queryRunner.query(`DROP TABLE "temporary_tax"`);
        await queryRunner.query(`ALTER TABLE "recurring_income" RENAME TO "temporary_recurring_income"`);
        await queryRunner.query(`CREATE TABLE "recurring_income" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "description" text NOT NULL, "amount" decimal(10,2) NOT NULL, "startDate" date NOT NULL, "frequency" text NOT NULL, "skipAmount" integer NOT NULL DEFAULT (0), "status" boolean NOT NULL DEFAULT (1), "userId" integer NOT NULL, "currencyId" integer, "accountId" integer)`);
        await queryRunner.query(`INSERT INTO "recurring_income"("id", "description", "amount", "startDate", "frequency", "skipAmount", "status", "userId", "currencyId", "accountId") SELECT "id", "description", "amount", "startDate", "frequency", "skipAmount", "status", "userId", "currencyId", "accountId" FROM "temporary_recurring_income"`);
        await queryRunner.query(`DROP TABLE "temporary_recurring_income"`);
        await queryRunner.query(`ALTER TABLE "account" RENAME TO "temporary_account"`);
        await queryRunner.query(`CREATE TABLE "account" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "balance" decimal(10,2) NOT NULL, "userId" integer NOT NULL, "currencyId" integer)`);
        await queryRunner.query(`INSERT INTO "account"("id", "name", "balance", "userId", "currencyId") SELECT "id", "name", "balance", "userId", "currencyId" FROM "temporary_account"`);
        await queryRunner.query(`DROP TABLE "temporary_account"`);
        await queryRunner.query(`DROP INDEX "IDX_a95e949168be7b7ece1a2382fe"`);
        await queryRunner.query(`ALTER TABLE "user" RENAME TO "temporary_user"`);
        await queryRunner.query(`CREATE TABLE "user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "uuid" text NOT NULL, "username" text NOT NULL, "email" text, "isAdmin" boolean NOT NULL DEFAULT (0), "passwordHash" text NOT NULL, "settingsId" integer NOT NULL, CONSTRAINT "REL_390395c3d8592e3e8d8422ce85" UNIQUE ("settingsId"))`);
        await queryRunner.query(`INSERT INTO "user"("id", "uuid", "username", "email", "isAdmin", "passwordHash", "settingsId") SELECT "id", "uuid", "username", "email", "isAdmin", "passwordHash", "settingsId" FROM "temporary_user"`);
        await queryRunner.query(`DROP TABLE "temporary_user"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a95e949168be7b7ece1a2382fe" ON "user" ("uuid") `);
        await queryRunner.query(`DROP INDEX "IDX_302808fcd211d51ffaff57edf8"`);
        await queryRunner.query(`DROP INDEX "IDX_ae2ca2a322385d5d0461bcb908"`);
        await queryRunner.query(`DROP TABLE "expense_taxes_tax"`);
        await queryRunner.query(`DROP INDEX "IDX_6b8337a489f9c302f23e1f5efd"`);
        await queryRunner.query(`DROP INDEX "IDX_ae12db69fd3a32f20aa527ff67"`);
        await queryRunner.query(`DROP TABLE "recurring_expense_taxes_tax"`);
        await queryRunner.query(`DROP TABLE "api_key"`);
        await queryRunner.query(`DROP TABLE "exchange_rate"`);
        await queryRunner.query(`DROP TABLE "expense"`);
        await queryRunner.query(`DROP TABLE "income"`);
        await queryRunner.query(`DROP TABLE "recurring_expense"`);
        await queryRunner.query(`DROP TABLE "payment_method"`);
        await queryRunner.query(`DROP TABLE "tax"`);
        await queryRunner.query(`DROP TABLE "recurring_income"`);
        await queryRunner.query(`DROP TABLE "account"`);
        await queryRunner.query(`DROP TABLE "currency"`);
        await queryRunner.query(`DROP INDEX "IDX_a95e949168be7b7ece1a2382fe"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "user_settings"`);
    }

}
