name: Docker Image CI (release)

on:
  release:
    types: [ "published" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker Image and publish to GHCR
      uses: macbre/push-to-ghcr@master
      with:
        image_name: ${{ github.repository }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        image_tag: ${{ github.event.release.tag_name }},latest
    - name: Clean up untagged images
      uses: dataaxiom/ghcr-cleanup-action@v1
      with:
        delete-untagged: true
