name: Docker Image CI (development)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker Image and publish to GHCR
      uses: macbre/push-to-ghcr@master
      with:
        image_name: ${{ github.repository }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        image_tag: develop
